heat_template_version: 2018-08-31
description: Multi-resource deployment

resources:
  network:
    type: OS::Neutron::Net
    properties:
      name: heat-network
  
  subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: network }
      cidr: 192.168.1.0/24
      gateway_ip: 192.168.1.1
  
  server:
    type: OS::Nova::Server
    properties:
      name: multi-resource-server
      image: cirros
      flavor: m1.tiny
      networks:
        - network: { get_resource: network }
